 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cTe8CzyQoKQq4TY99GU8JnT4LgzLiNQ',
    appId: '1:259987512421:web:d948e64d55fda92977ba8c',
    messagingSenderId: '259987512421',
    projectId: 'arther-chat-app',
    authDomain: 'arther-chat-app.firebaseapp.com',
    storageBucket: 'arther-chat-app.firebasestorage.app',
    measurementId: 'G-6W86TP3CRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWGBI48dwg8kMHgu4jKHg_fqr9gukgmQk',
    appId: '1:259987512421:android:037e0eb1aa112ec877ba8c',
    messagingSenderId: '259987512421',
    projectId: 'arther-chat-app',
    storageBucket: 'arther-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-OE_38ozYJx0V6InwsFP23KKciHsNuU',
    appId: '1:259987512421:ios:669eef8c9d04a53477ba8c',
    messagingSenderId: '259987512421',
    projectId: 'arther-chat-app',
    storageBucket: 'arther-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.artherChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp-OE_38ozYJx0V6InwsFP23KKciHsNuU',
    appId: '1:259987512421:ios:669eef8c9d04a53477ba8c',
    messagingSenderId: '259987512421',
    projectId: 'arther-chat-app',
    storageBucket: 'arther-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.artherChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9cTe8CzyQoKQq4TY99GU8JnT4LgzLiNQ',
    appId: '1:259987512421:web:ef5fcc1ea53fb5cc77ba8c',
    messagingSenderId: '259987512421',
    projectId: 'arther-chat-app',
    authDomain: 'arther-chat-app.firebaseapp.com',
    storageBucket: 'arther-chat-app.firebasestorage.app',
    measurementId: 'G-HPXR5S86EG',
  );
}
